CREATE TABLE core.resource_entities
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      BIGINT NOT NULL,
    storage_kind TEXT   NOT NULL
        CHECK (storage_kind IN ('tree', 'library_item')),

    CONSTRAINT uq_resource_entities_id_site UNIQUE (id, site_id),
    CONSTRAINT fk_resource_entities_site
        FOREIGN KEY (site_id)
            REFERENCES core.sites (id)
            ON DELETE CASCADE
);

INSERT INTO core.resource_entities (id, site_id, storage_kind)
SELECT id, site_id, 'tree'
FROM core.resources
ORDER BY id;

SELECT setval(
    pg_get_serial_sequence('core.resource_entities', 'id'),
    greatest(coalesce((SELECT max(id) FROM core.resource_entities), 1), 1),
    EXISTS (SELECT 1 FROM core.resource_entities)
);

ALTER TABLE core.resources
    ALTER COLUMN id SET DEFAULT nextval('core.resource_entities_id_seq'),
    ADD COLUMN type_settings JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(type_settings) = 'object'),
    ADD CONSTRAINT fk_resources_entity_site
        FOREIGN KEY (id, site_id)
            REFERENCES core.resource_entities (id, site_id)
            ON DELETE CASCADE;

ALTER TABLE core.resources
    DROP CONSTRAINT fk_resources_target_site,
    ADD CONSTRAINT fk_resources_target_site
        FOREIGN KEY (target_resource_id, site_id)
            REFERENCES core.resource_entities (id, site_id)
            ON DELETE NO ACTION;

ALTER TABLE core.resource_widgets
    DROP CONSTRAINT fk_resource_widgets_resource,
    ADD CONSTRAINT fk_resource_widgets_resource
        FOREIGN KEY (resource_id)
            REFERENCES core.resource_entities (id)
            ON DELETE CASCADE;

CREATE TABLE core.resource_field_values
(
    resource_id    BIGINT  NOT NULL,
    site_id        BIGINT  NOT NULL,
    field_key      TEXT    NOT NULL
        CHECK (field_key = btrim(field_key) AND field_key <> ''),
    position       INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0),
    is_multi       BOOLEAN NOT NULL DEFAULT FALSE,
    value_kind     TEXT    NOT NULL
        CHECK (value_kind IN ('string', 'integer', 'float', 'boolean', 'timestamp', 'reference', 'json')),
    value_string   TEXT        NULL,
    value_integer  BIGINT      NULL,
    value_float    DOUBLE PRECISION NULL,
    value_boolean  BOOLEAN     NULL,
    value_timestamp TIMESTAMPTZ NULL,
    value_reference BIGINT     NULL,
    value_json     JSONB       NULL,

    PRIMARY KEY (resource_id, field_key, position),
    CONSTRAINT fk_resource_field_values_entity_site
        FOREIGN KEY (resource_id, site_id)
            REFERENCES core.resource_entities (id, site_id)
            ON DELETE CASCADE,
    CONSTRAINT ck_resource_field_values_typed
        CHECK (num_nonnulls(
            value_string, value_integer, value_float, value_boolean,
            value_timestamp, value_reference, value_json
        ) = 1)
);

WITH expanded AS (
    SELECT
        resource.id AS resource_id,
        resource.site_id,
        entry.key AS field_key,
        coalesce(array_item.ordinality - 1, 0)::integer AS position,
        coalesce(array_item.value, entry.value) AS value,
        jsonb_typeof(entry.value) = 'array' AS is_multi
    FROM core.resources AS resource
    CROSS JOIN LATERAL jsonb_each(resource.settings) AS entry(key, value)
    LEFT JOIN LATERAL jsonb_array_elements(
        CASE WHEN jsonb_typeof(entry.value) = 'array' THEN entry.value ELSE '[]'::jsonb END
    ) WITH ORDINALITY AS array_item(value, ordinality) ON TRUE
    WHERE jsonb_typeof(entry.value) <> 'array' OR array_item.value IS NOT NULL
), classified AS (
    SELECT *,
        CASE
            WHEN jsonb_typeof(value) = 'string' THEN 'string'
            WHEN jsonb_typeof(value) = 'number' AND value::text ~ '^-?[0-9]+$' THEN 'integer'
            WHEN jsonb_typeof(value) = 'number' THEN 'float'
            WHEN jsonb_typeof(value) = 'boolean' THEN 'boolean'
            ELSE 'json'
        END AS value_kind
    FROM expanded
)
INSERT INTO core.resource_field_values (
    resource_id, site_id, field_key, position, is_multi, value_kind,
    value_string, value_integer, value_float, value_boolean, value_json
)
SELECT
    resource_id,
    site_id,
    field_key,
    position,
    is_multi,
    value_kind,
    CASE WHEN value_kind = 'string' THEN value #>> '{}' END,
    CASE WHEN value_kind = 'integer' THEN (value #>> '{}')::bigint END,
    CASE WHEN value_kind = 'float' THEN (value #>> '{}')::double precision END,
    CASE WHEN value_kind = 'boolean' THEN (value #>> '{}')::boolean END,
    CASE WHEN value_kind = 'json' THEN value END
FROM classified;

UPDATE core.resource_field_values AS value
SET value_kind = 'reference',
    value_reference = value.value_integer,
    value_integer = NULL
FROM core.file_field_references AS reference
WHERE reference.owner_kind = 'resource'
  AND reference.owner_id = value.resource_id
  AND reference.field_key = value.field_key;

ALTER TABLE core.resources DROP COLUMN settings;

CREATE INDEX idx_resource_field_values_string
    ON core.resource_field_values (site_id, field_key, value_string, resource_id)
    WHERE value_kind = 'string';
CREATE INDEX idx_resource_field_values_integer
    ON core.resource_field_values (site_id, field_key, value_integer, resource_id)
    WHERE value_kind = 'integer';
CREATE INDEX idx_resource_field_values_float
    ON core.resource_field_values (site_id, field_key, value_float, resource_id)
    WHERE value_kind = 'float';
CREATE INDEX idx_resource_field_values_boolean
    ON core.resource_field_values (site_id, field_key, value_boolean, resource_id)
    WHERE value_kind = 'boolean';
CREATE INDEX idx_resource_field_values_timestamp
    ON core.resource_field_values (site_id, field_key, value_timestamp, resource_id)
    WHERE value_kind = 'timestamp';
CREATE INDEX idx_resource_field_values_reference
    ON core.resource_field_values (site_id, field_key, value_reference, resource_id)
    WHERE value_kind = 'reference';

CREATE TABLE core.library_item_routes
(
    resource_id BIGINT PRIMARY KEY,
    site_id     BIGINT NOT NULL,
    library_id  BIGINT NOT NULL,
    slug        TEXT   NOT NULL CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),

    CONSTRAINT uq_library_item_routes_slug UNIQUE (library_id, slug),
    CONSTRAINT fk_library_item_routes_entity_site
        FOREIGN KEY (resource_id, site_id)
            REFERENCES core.resource_entities (id, site_id)
            ON DELETE CASCADE,
    CONSTRAINT fk_library_item_routes_library_site
        FOREIGN KEY (library_id, site_id)
            REFERENCES core.resources (id, site_id)
            ON DELETE CASCADE
);

CREATE TABLE core.library_items
(
    id              BIGINT      NOT NULL,
    site_id         BIGINT      NOT NULL,
    library_id      BIGINT      NOT NULL,
    partition_at    TIMESTAMPTZ NOT NULL,
    template        TEXT        NULL,
    content_type    TEXT        NULL DEFAULT 'html',
    title           TEXT        NOT NULL CHECK (btrim(title) <> ''),
    slug            TEXT        NOT NULL CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    annotation      TEXT        NOT NULL DEFAULT '',
    content         TEXT        NOT NULL DEFAULT '',
    image_media_id  BIGINT      NULL,
    is_public       BOOLEAN     NOT NULL DEFAULT TRUE,
    is_searchable   BOOLEAN     NOT NULL DEFAULT TRUE,
    published_at    TIMESTAMPTZ NULL,
    unpublished_at  TIMESTAMPTZ NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      BIGINT      NULL,
    updated_by      BIGINT      NULL,
    deleted_at      TIMESTAMPTZ NULL,
    deleted_by      BIGINT      NULL,

    PRIMARY KEY (id, library_id, partition_at),
    CONSTRAINT fk_library_items_entity_site
        FOREIGN KEY (id, site_id)
            REFERENCES core.resource_entities (id, site_id)
            ON DELETE CASCADE,
    CONSTRAINT fk_library_items_library_site
        FOREIGN KEY (library_id, site_id)
            REFERENCES core.resources (id, site_id)
            ON DELETE CASCADE,
    CONSTRAINT fk_library_items_image_media
        FOREIGN KEY (image_media_id)
            REFERENCES core.media (id)
            ON DELETE RESTRICT,
    CONSTRAINT fk_library_items_created_by
        FOREIGN KEY (created_by) REFERENCES core.users (id) ON DELETE SET NULL,
    CONSTRAINT fk_library_items_updated_by
        FOREIGN KEY (updated_by) REFERENCES core.users (id) ON DELETE SET NULL,
    CONSTRAINT fk_library_items_deleted_by
        FOREIGN KEY (deleted_by) REFERENCES core.users (id) ON DELETE SET NULL,
    CONSTRAINT ck_library_items_publication_window
        CHECK (published_at IS NULL OR unpublished_at IS NULL OR unpublished_at > published_at)
) PARTITION BY HASH (library_id);

CREATE TABLE core.library_items_h0
    PARTITION OF core.library_items
    FOR VALUES WITH (MODULUS 8, REMAINDER 0)
    PARTITION BY RANGE (partition_at);

CREATE TABLE core.library_items_h0_before_2020
    PARTITION OF core.library_items_h0
    FOR VALUES FROM (MINVALUE) TO ('2020-01-01 00:00:00+00');

CREATE TABLE core.library_items_h0_2020s
    PARTITION OF core.library_items_h0
    FOR VALUES FROM ('2020-01-01 00:00:00+00') TO ('2030-01-01 00:00:00+00');

CREATE TABLE core.library_items_h0_after_2030
    PARTITION OF core.library_items_h0
    FOR VALUES FROM ('2030-01-01 00:00:00+00') TO (MAXVALUE);

CREATE TABLE core.library_items_h1
    PARTITION OF core.library_items
    FOR VALUES WITH (MODULUS 8, REMAINDER 1)
    PARTITION BY RANGE (partition_at);

CREATE TABLE core.library_items_h1_before_2020
    PARTITION OF core.library_items_h1
    FOR VALUES FROM (MINVALUE) TO ('2020-01-01 00:00:00+00');

CREATE TABLE core.library_items_h1_2020s
    PARTITION OF core.library_items_h1
    FOR VALUES FROM ('2020-01-01 00:00:00+00') TO ('2030-01-01 00:00:00+00');

CREATE TABLE core.library_items_h1_after_2030
    PARTITION OF core.library_items_h1
    FOR VALUES FROM ('2030-01-01 00:00:00+00') TO (MAXVALUE);

CREATE TABLE core.library_items_h2
    PARTITION OF core.library_items
    FOR VALUES WITH (MODULUS 8, REMAINDER 2)
    PARTITION BY RANGE (partition_at);

CREATE TABLE core.library_items_h2_before_2020
    PARTITION OF core.library_items_h2
    FOR VALUES FROM (MINVALUE) TO ('2020-01-01 00:00:00+00');

CREATE TABLE core.library_items_h2_2020s
    PARTITION OF core.library_items_h2
    FOR VALUES FROM ('2020-01-01 00:00:00+00') TO ('2030-01-01 00:00:00+00');

CREATE TABLE core.library_items_h2_after_2030
    PARTITION OF core.library_items_h2
    FOR VALUES FROM ('2030-01-01 00:00:00+00') TO (MAXVALUE);

CREATE TABLE core.library_items_h3
    PARTITION OF core.library_items
    FOR VALUES WITH (MODULUS 8, REMAINDER 3)
    PARTITION BY RANGE (partition_at);

CREATE TABLE core.library_items_h3_before_2020
    PARTITION OF core.library_items_h3
    FOR VALUES FROM (MINVALUE) TO ('2020-01-01 00:00:00+00');

CREATE TABLE core.library_items_h3_2020s
    PARTITION OF core.library_items_h3
    FOR VALUES FROM ('2020-01-01 00:00:00+00') TO ('2030-01-01 00:00:00+00');

CREATE TABLE core.library_items_h3_after_2030
    PARTITION OF core.library_items_h3
    FOR VALUES FROM ('2030-01-01 00:00:00+00') TO (MAXVALUE);

CREATE TABLE core.library_items_h4
    PARTITION OF core.library_items
    FOR VALUES WITH (MODULUS 8, REMAINDER 4)
    PARTITION BY RANGE (partition_at);

CREATE TABLE core.library_items_h4_before_2020
    PARTITION OF core.library_items_h4
    FOR VALUES FROM (MINVALUE) TO ('2020-01-01 00:00:00+00');

CREATE TABLE core.library_items_h4_2020s
    PARTITION OF core.library_items_h4
    FOR VALUES FROM ('2020-01-01 00:00:00+00') TO ('2030-01-01 00:00:00+00');

CREATE TABLE core.library_items_h4_after_2030
    PARTITION OF core.library_items_h4
    FOR VALUES FROM ('2030-01-01 00:00:00+00') TO (MAXVALUE);

CREATE TABLE core.library_items_h5
    PARTITION OF core.library_items
    FOR VALUES WITH (MODULUS 8, REMAINDER 5)
    PARTITION BY RANGE (partition_at);

CREATE TABLE core.library_items_h5_before_2020
    PARTITION OF core.library_items_h5
    FOR VALUES FROM (MINVALUE) TO ('2020-01-01 00:00:00+00');

CREATE TABLE core.library_items_h5_2020s
    PARTITION OF core.library_items_h5
    FOR VALUES FROM ('2020-01-01 00:00:00+00') TO ('2030-01-01 00:00:00+00');

CREATE TABLE core.library_items_h5_after_2030
    PARTITION OF core.library_items_h5
    FOR VALUES FROM ('2030-01-01 00:00:00+00') TO (MAXVALUE);

CREATE TABLE core.library_items_h6
    PARTITION OF core.library_items
    FOR VALUES WITH (MODULUS 8, REMAINDER 6)
    PARTITION BY RANGE (partition_at);

CREATE TABLE core.library_items_h6_before_2020
    PARTITION OF core.library_items_h6
    FOR VALUES FROM (MINVALUE) TO ('2020-01-01 00:00:00+00');

CREATE TABLE core.library_items_h6_2020s
    PARTITION OF core.library_items_h6
    FOR VALUES FROM ('2020-01-01 00:00:00+00') TO ('2030-01-01 00:00:00+00');

CREATE TABLE core.library_items_h6_after_2030
    PARTITION OF core.library_items_h6
    FOR VALUES FROM ('2030-01-01 00:00:00+00') TO (MAXVALUE);

CREATE TABLE core.library_items_h7
    PARTITION OF core.library_items
    FOR VALUES WITH (MODULUS 8, REMAINDER 7)
    PARTITION BY RANGE (partition_at);

CREATE TABLE core.library_items_h7_before_2020
    PARTITION OF core.library_items_h7
    FOR VALUES FROM (MINVALUE) TO ('2020-01-01 00:00:00+00');

CREATE TABLE core.library_items_h7_2020s
    PARTITION OF core.library_items_h7
    FOR VALUES FROM ('2020-01-01 00:00:00+00') TO ('2030-01-01 00:00:00+00');

CREATE TABLE core.library_items_h7_after_2030
    PARTITION OF core.library_items_h7
    FOR VALUES FROM ('2030-01-01 00:00:00+00') TO (MAXVALUE);
CREATE INDEX idx_library_items_library_created
    ON core.library_items (library_id, created_at DESC, id DESC);
CREATE INDEX idx_library_items_library_publication
    ON core.library_items (library_id, is_public, published_at DESC, id DESC);
